<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerALe9kh8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerALe9kh8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerALe9kh8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerALe9kh8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerALe9kh8\App_KernelDevDebugContainer([
    'container.build_hash' => 'ALe9kh8',
    'container.build_id' => '3c96dd21',
    'container.build_time' => 1583592561,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerALe9kh8');
