<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEt1xErg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEt1xErg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEt1xErg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEt1xErg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEt1xErg\App_KernelDevDebugContainer([
    'container.build_hash' => 'Et1xErg',
    'container.build_id' => 'e3c53aa6',
    'container.build_time' => 1583508860,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEt1xErg');
